### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mateusfg7** [mateusfg7/textAnalysis#3]
- [x] **feelingAnalisys.py** - _mudar o valor obtido de decimal para inteiro_
- [x] _dependências do python_
`python3 -m pip install -r requeriments.txt`
- [x] **frequencieOfWords.py** - _adicionar gráfico indicando a frequência de cada palavra com a biblioteca `matplotlib`_
- [x] _Poder passar uma única palavra/frase em vez de um arquivo com um texto_
- [x] _Adicionar requisição  de credencial da Algorithmia privada do usuário_

**Comment by ark-c3** [comment]
coment
